-- Add new columns to carriers table
ALTER TABLE public.carriers 
ADD COLUMN IF NOT EXISTS display_name text,
ADD COLUMN IF NOT EXISTS state_availability text[];

-- Insert/Update all 68 carriers
INSERT INTO public.carriers (code, name, display_name, notes, is_active, product_tags) VALUES
('aetna', 'Aetna', 'Aetna', NULL, true, '{}'),
('aetna_ma', 'Aetna MA', 'Aetna MA', 'Medicare Advantage - NV specific', true, '{}'),
('aetna_ms', 'Aetna MS', 'Aetna MS', 'Medicare Supplement - NV specific', true, '{}'),
('agla', 'AGLA Life with Living Benefits', 'AGLA', NULL, true, '{}'),
('alignment', 'Alignment Health', 'Alignment Health', NULL, true, '{}'),
('american_equity', 'American Equity', 'American Equity', NULL, true, '{}'),
('american_general', 'American General Life', 'American General', NULL, true, '{}'),
('americo', 'Americo', 'Americo', NULL, true, '{}'),
('anthem', 'Anthem', 'Anthem', 'includes Empire, Amerigroup, CareMore', true, '{}'),
('assurity', 'Assurity', 'Assurity', NULL, true, '{}'),
('athene', 'Athene', 'Athene', NULL, true, '{}'),
('baltimore_life', 'Baltimore Life', 'Baltimore Life', NULL, true, '{}'),
('bankers_fidelity', 'Bankers Fidelity Life', 'Bankers Fidelity', NULL, true, '{}'),
('baycare', 'BayCare', 'BayCare', NULL, true, '{}'),
('bcbs_michigan', 'Blue Cross Blue Shield of Michigan', 'BCBS Michigan', NULL, true, '{}'),
('bright_health', 'Bright Health', 'Bright Health', NULL, true, '{}'),
('brighthouse', 'Brighthouse Financial', 'Brighthouse', NULL, true, '{}'),
('capitol_life', 'Capitol Life', 'Capitol Life', NULL, true, '{}'),
('cigna', 'Cigna', 'Cigna', NULL, true, '{}'),
('cigna_healthspring', 'Cigna HealthSpring', 'Cigna HealthSpring', 'Bravo Health', true, '{}'),
('clover', 'Clover Health', 'Clover Health', NULL, true, '{}'),
('columbian_mutual', 'Columbian Mutual Life', 'Columbian Mutual', NULL, true, '{}'),
('combined', 'Combined Insurance Company of America', 'Combined', NULL, true, '{}'),
('devoted', 'Devoted Health', 'Devoted Health', NULL, true, '{}'),
('emblem', 'Emblem', 'Emblem', 'includes Connecticare', true, '{}'),
('equitable', 'Equitable', 'Equitable', NULL, true, '{}'),
('equitrust', 'EquiTrust', 'EquiTrust', NULL, true, '{}'),
('essence', 'Essence', 'Essence', NULL, true, '{}'),
('fg', 'F&G', 'F&G', NULL, true, '{}'),
('foresters', 'Foresters Financial', 'Foresters', NULL, true, '{}'),
('freedom_health', 'Freedom Health', 'Freedom Health', 'includes Optimum', true, '{}'),
('global_atlantic', 'Global Atlantic', 'Global Atlantic', NULL, true, '{}'),
('great_american', 'Great American', 'Great American', NULL, true, '{}'),
('great_western', 'Great Western', 'Great Western', NULL, true, '{}'),
('gtl', 'Guarantee Trust Life', 'GTL', NULL, true, '{}'),
('healthfirst', 'HealthFirst', 'HealthFirst', NULL, true, '{}'),
('humana', 'Humana', 'Humana', NULL, true, '{}'),
('independence_bc', 'Independence Blue Cross', 'Independence BC', NULL, true, '{}'),
('john_hancock', 'John Hancock', 'John Hancock', NULL, true, '{}'),
('lincoln', 'Lincoln Financial', 'Lincoln Financial', NULL, true, '{}'),
('lumico', 'LUMICO', 'LUMICO', NULL, true, '{}'),
('medico', 'Medico', 'Medico', NULL, true, '{}'),
('molina', 'Molina Healthcare', 'Molina', NULL, true, '{}'),
('mutual_omaha', 'Mutual of Omaha', 'Mutual of Omaha', NULL, true, '{}'),
('national_care_dental', 'National Care Dental', 'National Care Dental', NULL, true, '{}'),
('ngl', 'National Guardian Life', 'NGL', NULL, true, '{}'),
('nlg', 'National Life Group', 'NLG', NULL, true, '{}'),
('national_western', 'National Western', 'National Western', NULL, true, '{}'),
('nationwide', 'Nationwide', 'Nationwide', NULL, true, '{}'),
('nacolah', 'North American', 'North American', 'NACOLAH', true, '{}'),
('oceanview', 'Oceanview', 'Oceanview', NULL, true, '{}'),
('oscar', 'Oscar Health', 'Oscar Health', NULL, true, '{}'),
('protective', 'Protective Life', 'Protective', NULL, true, '{}'),
('prudential', 'Prudential', 'Prudential', NULL, true, '{}'),
('regence', 'Regence', 'Regence', NULL, true, '{}'),
('royal_neighbors', 'Royal Neighbors of America', 'Royal Neighbors', NULL, true, '{}'),
('scan', 'SCAN', 'SCAN', NULL, true, '{}'),
('selecthealth', 'SelectHealth', 'SelectHealth', NULL, true, '{}'),
('sentinel', 'Sentinel Security Life', 'Sentinel', NULL, true, '{}'),
('simply', 'Simply Healthcare', 'Simply Healthcare', NULL, true, '{}'),
('sons_of_norway', 'Sons of Norway', 'Sons of Norway', NULL, true, '{}'),
('the_standard', 'The Standard', 'The Standard', NULL, true, '{}'),
('transamerica', 'Transamerica', 'Transamerica', NULL, true, '{}'),
('united_home_life', 'United Home Life', 'United Home Life', NULL, true, '{}'),
('united_security', 'United Security Assurance', 'United Security', NULL, true, '{}'),
('uhc', 'UnitedHealthcare', 'UnitedHealthcare', NULL, true, '{}'),
('usic', 'USIC', 'USIC', NULL, true, '{}'),
('washington_national', 'Washington National', 'Washington National', NULL, true, '{}'),
('wellcare', 'WellCare', 'WellCare', NULL, true, '{}'),
('william_penn', 'William Penn', 'William Penn', NULL, true, '{}')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  display_name = EXCLUDED.display_name,
  notes = COALESCE(EXCLUDED.notes, carriers.notes),
  is_active = true;